name: Publish website

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    # Specify the target branch (optional)
    - uses: jeffreytse/jekyll-deploy-action@v0.5.1
      with:
        provider: 'github'
        token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
        repository: ''             # Default is current repository
        branch: 'gh-pages'         # Default is gh-pages for github provider
        jekyll_src: './'           # Default is root directory
        jekyll_cfg: '_config.yml'  # Default is _config.yml
        jekyll_baseurl: ''         # Default is according to _config.yml
        bundler_ver: ''         # Default is latest bundler version
        cname: ''                  # Default is to not use a cname
        actor: ''                  # Default is the GITHUB_ACTOR
        pre_build_commands: ''     # Installing additional dependencies (Arch Linux)