name: Publish website

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v4.0.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
  
    - name: setup ruby
        uses: ruby/setup-ruby@v1.192.0
        with:
          ruby-version: 2.7 # can change this to whatever version you prefer

    - name: install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2

    - name: deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # if the repo you are deploying to is <username>.github.io, uncomment the line below.
          # if you are including the line below, make sure your source files are NOT in the master branch:
          publish_branch: 'gh-pages'